app/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SelectField, BooleanField, SubmitField
# from flask.ext.wtf.html5 import NumberInput
from wtforms.widgets import TextArea
from wtforms.validators import DataRequired, length


class DataForm(FlaskForm):

    GENDER_VALUES = ['Male', 'Female' ]

    VEHICLE_AGE_VALUES = ["> 2 Years", "1-2 Year", "< 1 Year"]

    REGION_CODE_VALUES = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52]

    POLICY_SALES_CHANNEL_VALUES = [  1,   2,   3,   4,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  73,  74,  75,  76,  78,  79,  80,  81,
        82,  83,  84,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
       122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
       135, 136, 137, 138, 139, 140, 143, 144, 145, 146, 147, 148, 149,
       150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 163]

    DEFAULT = {"Gender":"Male",
            "Age":29,
            "Driving_License":True,
            "Region_Code":REGION_CODE_VALUES[0],
            "Previously_Insured":False,
            "Vehicle_Age":"> 2 Years",
            "Vehicle_Damage":True,
            "Annual_Premium":1200.0,
            "Policy_Sales_Channel":POLICY_SALES_CHANNEL_VALUES[0],
            "Vintage": 217}
    """
    DEFAULT = {"Gender":None,
            "Age":None,
            "Driving_License":None,
            "Region_Code":None,
            "Previously_Insured":None,
            "Vehicle_Age":None,
            "Vehicle_Damage":None,
            "Annual_Premium":None,
            "Policy_Sales_Channel":None,
            "Vintage": None}
    """

    BASE_VALIDATORS = [DataRequired()]

    gender = SelectField('Gender', choices=GENDER_VALUES, validators=BASE_VALIDATORS, default=DEFAULT["Gender"])
    age = IntegerField(validators=BASE_VALIDATORS, default=DEFAULT["Age"])
    driving_license = BooleanField('Driving License', default=DEFAULT["Driving_License"])
    region_code = SelectField('Region Code', choices=REGION_CODE_VALUES, validators=BASE_VALIDATORS, default=DEFAULT["Region_Code"])
    previously_insured = BooleanField('Previously Insured', default=DEFAULT["Previously_Insured"])
    vehicle_age = SelectField('Vehicle Age', choices=VEHICLE_AGE_VALUES, validators=BASE_VALIDATORS, default=DEFAULT["Vehicle_Age"])
    vehicle_damage = BooleanField('Vehicle Damage', default=DEFAULT["Vehicle_Damage"])
    annual_premium = StringField('Annual Premium', validators=BASE_VALIDATORS, default=DEFAULT["Annual_Premium"] )
    policy_sales_channel = SelectField('Policy Sales Channel', choices=POLICY_SALES_CHANNEL_VALUES, validators=BASE_VALIDATORS, default=DEFAULT["Policy_Sales_Channel"])
    vintage = IntegerField(validators=BASE_VALIDATORS, default=DEFAULT["Vintage"])
    submit = SubmitField('Predict')

app/app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_dropzone import Dropzone
from flask_session import Session

bootstrap = Bootstrap()
dropzone = Dropzone()
session = Session()

def create_app():

    app = Flask(__name__)
    app.secret_key = "a very safe secret key"
    app.config["SECRET_KEY"] = app.secret_key
    app.config['SESSION_TYPE'] = 'filesystem'
    app.config["DROPZONE_ALLOWED_FILE_CUSTOM"] = True
    app.config["DROPZONE_ALLOWED_FILE_TYPE"] = ".csv"
    
    bootstrap.init_app(app)
    dropzone.init_app(app)
    session.init_app(app)

    from .api import api as api_blueprint
    app.register_blueprint(api_blueprint, url_prefix='/api/v1')

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/app/api/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

from . import predict

app/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/app/main/views.py
from flask import render_template, request, session
from flask_session import Session
from . import main
from .forms import DataForm
from ..ml import predict
import codecs


@main.route('/', methods=['GET', 'POST'])
def index():

    form = DataForm()

    if form.validate_on_submit():
        
        data = [{"Gender":form.gender.data,
                "Age":form.age.data,
                "Driving_License":form.driving_license.data,
                "Region_code":float(form.region_code.data),
                "Previously_Insured":form.previously_insured.data,
                "Vehicle_Age":form.vehicle_age.data,
                "Vehicle_Damage":form.vehicle_damage.data,
                "Annual_Premium":form.annual_premium.data,
                "Policy_Sales_Channel":float(form.policy_sales_channel.data),
                "Vintage": form.vintage.data}]

        response, confidence = predict(data)

        return render_template('index.html', form=form, response=response[0], confidence=confidence[0])

    return render_template('index.html', form=form)



@main.route('/batch', methods=['GET', 'POST'])
def batch():
    if request.method == 'POST':

        global data, response, confidence

        f = request.files.get('file')
        stream = codecs.iterdecode(f.stream, 'utf-8')

        data = []

        for line in stream:

            sample = line.replace("\n","").split(",")
            data.append(
                {"Gender": sample[0],
                 "Age": sample[1],
                 "Driving_License": sample[2],
                 "Region_code": float(sample[3]),
                 "Previously_Insured": sample[4],
                 "Vehicle_Age": sample[5],
                 "Vehicle_Damage": sample[6],
                 "Annual_Premium": sample[7],
                 "Policy_Sales_Channel": float(sample[8]),
                 "Vintage": sample[9]}
            )

        response, confidence = predict(data)

        session['data'] = data
        session['response'] =response
        session['confidence'] = confidence
        
    return render_template('batch.html')


@main.route('/result', methods=['GET', 'POST'])
def result():
    return render_template('result.html', data=session['data'], response=session['response'], confidence=session['confidence'])

app/app/templates/batch.html
{% extends "navbar.html" %}

{% block title %}Insurance Cross Selling Prediction{% endblock %}
{% block content %}

    <head>
        {{ dropzone.load_css() }}
    </head>
    <body>
        <div class="container">

        <h1>Multiple Predictions</h1>
        <h4>
            Get multiple predictions by uploading a csv file with your observations.
        </h4>
            <h4>Wanna test it ? Try with this <a href="static/sample.csv">sample csv file</a>.</h4>
        </div>
          {{ dropzone.create(action='main.batch') }}
          {{ dropzone.load_js() }}
          {{ dropzone.config(redirect_url=url_for('main.result'))}}
          {{ dropzone.style('margin:40px 80px 40px 80px; min-height: 400px;') }}

    </body>

{% endblock %}

app/app/templates/index.html
{% extends "navbar.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Insurance Cross Selling Prediction{% endblock %}
{% block content %}

    <div class="container">

        <h1>Insurance Cross Selling Prediction</h1>
        <p>
            This app estimates the opportunity for insurance cross-selling. 
            It uses information obtained from customers who have purchased an health insurance to predict whether they might be interested in purchasing a vehicle insurance as well.        </p>
        <p>
            The following is the information used by the system:
            <ul>
                <li><b>Gender:</b>gender of the customer</li>
                <li><b>Age:</b>age of the customer</li>
                <li><b>Driving License:</b>if the customer have a driving license</li>
                <li><b>Region Code:</b>unique code for the region of the customer</li>
                <li><b>Previously Insured:</b>if customer already has vehicle insurance</li>
                <li><b>Vehicle Age:</b>age of the vehicle</li>
                <li><b>Vehicle Damage:</b>if customer got his/her vehicle damaged in the past</li>
                <li><b>Annual premium:</b>the amount customer needs to pay as premium in the year</li>
                <li><b>Policy Sales Channel:</b>anonymized code for the channel of outreaching to the customer ie. Different Agents, Over Mail, Over Phone, In Person, etc.</li>
                <li><b>Vintage:</b>number of days, customer has been associated with the company</li>
            </ul>
        </p>

        <h3>Enter customer information:</h3>
        {{wtf.quick_form(form)}}

        <br/>

        {% if response==0 %}
            <h3>The customer <b>may not be interested</b> in a vehicle insurance with a probability of <b>{{(100*confidence)|round(2)}}%</b></h3>
        {% elif response==1 %}
            <h3>The customer <b>might be interested</b> in a vehicle insurance with a probability of <b>{{(100*confidence)|round(2)}}%</b></h3>
        {% endif %}

    </div>

{% endblock %}

app/app/templates/navbar.html
{% extends "bootstrap/base.html" %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Insurance Cross Selling Prediction</a>
        </div>
        <div class="navbar-collapse collapse">

            <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('main.index') }}">Single Prediction</a></li>
                    <li><a href="{{ url_for('main.batch') }}">Batch Prediction</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

app/app/templates/result.html
{% extends "navbar.html" %}

{% block title %}Insurance Cross Selling Prediction{% endblock %}
{% block content %}

    {% if response is defined %}
        <table class="table">

            <thead>
                <tr>
                    <!--<th>Observation ID</th>-->

                    {% for key in data[0] %}
                        <th>{{ key }}</th>
                    {% endfor %}

                    <th>Response</th>
                    <th>Confidence</th>
                </tr>
            </thead>

            <tbody>
            {% for _ in response %}
                {% set outer_loop = loop %}
                <tr>
                    <!--<td>Observation {{ loop.index }}</td>-->

                    {% for key in data[loop.index-1] %}
                        <td>{{ data[outer_loop.index-1][key] }}</td>
                    {% endfor %}

                    <td><b>{{ response[loop.index-1] }}</b></td>
                    <td><b>{{ (100*confidence[loop.index-1])|round(2)}}</b></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}

    </body>

    <a style="margin-left: 20px" href="{{ url_for('main.batch') }}">Back</a>

{% endblock %}